base_url = "https://www.contextgeneric.dev"

title = "Context-Generic Programming"

theme = "juice"

compile_sass = true

build_search_index = true

generate_feeds = true

[markdown]

highlight_code = true
highlight_theme = "visual-studio-dark"

[extra]

juice_logo_path = "cgp-logo.svg"

juice_logo_name = "Context-Generic Programming"

juice_extra_menu = [
    { title = "Blog", link = "/blog"},
    { title = "Book", link = "https://patterns.contextgeneric.dev"},
    { title = "GitHub", link = "https://github.com/contextgeneric/cgp"},
]